version: 2.1

default_docker: &default_docker
  docker:
      - image: circleci/node:13.8.0

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
  
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      # - add_ssh_keys:
      #     fingerprints: ["69:7e:38:86:68:24:e7:81:f7:c3:2d:28:30:ea:eb:c5", "00:8f:b2:21:89:de:dc:a1:f1:56:ca:67:93:c3:24:b9"]
      - run: 
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main-remote.yml


workflows:
  sharing-files:
    jobs:
      - configure_infrastructure
