version: 2.1

default_docker: &default_docker
  docker:
      - image: circleci/node:13.8.0

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
  
  configure_infrastructure:
    docker:
      - image: cimg/node:13.8.0 #python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["69:7e:38:86:68:24:e7:81:f7:c3:2d:28:30:ea:eb:c5"]
      - run: 
          name: Install Ansible
          command: |
            apt update
            apt upgrade -y
            apt install python3-pip -y
            pip3 install --upgrade pip
            pip3 install ansible
    #apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook main-remote.yml -i inventory.txt
#
workflows:
  sharing-files:
    jobs:
      - configure_infrastructure
