---
- name: "update apt package."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies"
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  npm:
    name: pm2
    global: yes
    production: yes

- name: "create ~/web dir"
  file:
    path: ~/web
    state: directory

- name: "copy files/index.js to ~/web/index.js"
  copy:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "start web server"
  shell: |
    pm2 start ~/web/index.js -f
